version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ~/Data/mongodb:/data/db
    ports:
      - "27017:27017"
  web:
    image: opetstudio/erevna-google-spreadsheet-loader:version1.0.0
    ports:
      - "4000:8080"
    links:
      - mongo
