version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: opetstudio/erevna-google-spreadsheet-loader:version1.0.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8080"
    links:
      - mongo
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "5000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager] #service only ever runs on a swarm manager – never a worker.
    networks:
      - webnet
  mongo:
    image: mongo
    volumes:
      - ~/Data/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - webnet
networks:
  webnet:
